name: ${project.name}
version: ${project.version}
description: '${project.description}'
author: Programie
website: ${project.url}
api-version: 1.20
main: com.selfcoders.savemyxp.SaveMyXP
permissions:
  savemyxp.*:
    children:
      - savemyxp.create
      - savemyxp.destroy-any
  savemyxp.create:
    description: 'Allow to create XP signs'
    default: true
  savemyxp.destroy-any:
    description: 'Allow to destroy any XP signs (not just your own)'
    default: op