name: Build package

on: push

permissions:
  contents: write

jobs:
  build:
    uses: programie/Workflows/.github/workflows/build-minecraft-plugin.yml@main
    secrets: inherit
    with:
      curseforge_id: 477368
      modrinth_id: CxvN2dLv
      game_versions: '>= 1.20.1'